name: Create Production Builds

on:
  push:
    branches: ['feature/pipelines']

jobs:
  run-eas-workflow:
    runs-on: ubuntu-latest
    env:
      EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - name: Lint
        run: npx expo lint

      - name: Test
        run: bun test

      # - name: Setup EAS
      #   uses: expo/expo-github-action@v8
      #   with:
      #     eas-version: latest
      #     token: ${{ secrets.EXPO_TOKEN }}